/* Generated by "click-buildtool elem2export" on Wed Feb  3 18:22:13 GMT 2010 */

#include <click/config.h>
#include <click/package.hh>
#include "../elements/wifi/settxrate.hh"
#include "../elements/standard/delayshaper.hh"
#include "../elements/local/toytcp.hh"
#include "../elements/wifi/filtertx.hh"
#include "../elements/threads/spinlockrelease.hh"
#include "../elements/test/listtest.hh"
#include "../elements/wifi/ethercount.hh"
#include "../elements/icmp/icmppingresponder.hh"
#include "../elements/test/biginttest.hh"
#include "../elements/local/tcpreflector.hh"
#include "../elements/ip/ipmirror.hh"
#include "../elements/analysis/toipsumdump.hh"
#include "../elements/wifi/station/beacontracker.hh"
#include "../elements/wifi/readanno.hh"
#include "../elements/ip/decipttl.hh"
#include "../elements/test/randomseed.hh"
#include "../elements/standard/hub.hh"
#include "../elements/wifi/wififragment.hh"
#include "../elements/local/bufconv.hh"
#include "../elements/analysis/fromipsumdump.hh"
#include "../elements/standard/striptonet.hh"
#include "../elements/standard/storedata.hh"
#include "../elements/wifi/station/proberequester.hh"
#include "../elements/wifi/linktable.hh"
#include "../elements/test/vectortest.hh"
#include "../elements/ip/ipfieldinfo.hh"
#include "../elements/local/forcetcp.hh"
#include "../elements/icmp/icmpsendpings.hh"
#include "../elements/standard/linkunqueue.hh"
#include "../elements/wifi/wepdecap.hh"
#include "../elements/wifi/wifidefrag.hh"
#include "../elements/standard/staticpullswitch.hh"
#include "../elements/standard/ratedunqueue.hh"
#include "../elements/standard/flowinfo.hh"
#include "../elements/ip/ipinputcombo.hh"
#include "../elements/analysis/ipsumdump_anno.hh"
#include "../elements/standard/randomsample.hh"
#include "../elements/ip/lookupiproutelinux.hh"
#include "../elements/ip/ipencap.hh"
#include "../elements/icmp/checkicmpheader.hh"
#include "../elements/ethernet/ethermirror.hh"
#include "../elements/wifi/fromhandler.hh"
#include "../elements/standard/dropbroadcasts.hh"
#include "../elements/standard/delayunqueue.hh"
#include "../elements/analysis/ipsumdump_tcp.hh"
#include "../elements/wifi/availablerates.hh"
#include "../elements/userlevel/todump.hh"
#include "../elements/standard/settimestamp.hh"
#include "../elements/local/forceip.hh"
#include "../elements/aqm/red.hh"
#include "../elements/standard/timedunqueue.hh"
#include "../elements/local/basic.hh"
#include "../elements/analysis/aggpktcounter.hh"
#include "../elements/userlevel/changeuid.hh"
#include "../elements/standard/drivermanager.hh"
#include "../elements/test/functiontest.hh"
#include "../elements/wifi/madwifirate.hh"
#include "../elements/standard/bwratedsplitter.hh"
#include "../elements/analysis/aggregatefirst.hh"
#include "../elements/test/clptest.hh"
#include "../elements/ip/fixipsrc.hh"
#include "../elements/tcpudp/settcpchecksum.hh"
#include "../elements/local/webgen.hh"
#include "../elements/local/reframe.hh"
#include "../elements/ip/setipchecksum.hh"
#include "../elements/standard/quicknotequeue.hh"
#include "../elements/app/ftpportmapper.hh"
#include "../elements/wifi/station/associationrequester.hh"
#include "../elements/test/comparepackets.hh"
#include "../elements/analysis/aggregatelast.hh"
#include "../elements/analysis/settimestampdelta.hh"
#include "../elements/standard/switch.hh"
#include "../elements/local/duppath.hh"
#include "../elements/ip/rfc2507c.hh"
#include "../elements/ip/getipaddress.hh"
#include <click/standard/errorelement.hh>
#include "../elements/standard/bandwidthmeter.hh"
#include <click/standard/alignmentinfo.hh>
#include "../elements/ip/ipaddrpairrewriter.hh"
#include "../elements/analysis/anonipaddr.hh"
#include "../elements/wifi/filterphyerr.hh"
#include "../elements/wifi/ap/associationresponder.hh"
#include "../elements/standard/devirtualizeinfo.hh"
#include "../elements/standard/burster.hh"
#include "../elements/ethernet/hostetherfilter.hh"
#include "../elements/standard/annotationinfo.hh"
#include "../elements/ip/rfc2507d.hh"
#include "../elements/analysis/fromnetflowsumdump.hh"
#include "../elements/standard/threadsafequeue.hh"
#include "../elements/standard/ratedsource.hh"
#include "../elements/ip/ipreassembler.hh"
#include "../elements/ethernet/etherpausesource.hh"
#include "../elements/wifi/wepencap.hh"
#include "../elements/wifi/extradecap.hh"
#include "../elements/standard/rrsched.hh"
#include "../elements/standard/meter.hh"
#include "../elements/analysis/fromcapdump.hh"
#include "../elements/wifi/station/beaconscanner.hh"
#include "../elements/standard/staticswitch.hh"
#include "../elements/local/tcpconn.hh"
#include "../elements/local/copyflowid.hh"
#include "../elements/ip/truncateippayload.hh"
#include "../elements/ip/ipgwoptions.hh"
#include "../elements/ip/directiplookup.hh"
#include "../elements/wifi/pushanno.hh"
#include "../elements/standard/simplequeue.hh"
#include "../elements/standard/bwratedunqueue.hh"
#include "../elements/ip/ipclassifier.hh"
#include "../elements/local/pad.hh"
#include "../elements/ip/siphmapper.hh"
#include "../elements/icmp/icmppingrewriter.hh"
#include "../elements/wifi/settxpower.hh"
#include "../elements/analysis/aggregateip.hh"
#include "../elements/standard/tee.hh"
#include "../elements/standard/frontdropqueue.hh"
#include "../elements/local/forceudp.hh"
#include "../elements/ip/markipce.hh"
#include "../elements/analysis/ipsumdump_ip.hh"
#include "../elements/wifi/extraencap.hh"
#include "../elements/ip/radixiplookup.hh"
#include "../elements/standard/timedsource.hh"
#include "../elements/ip/ipprint.hh"
#include "../elements/icmp/icmperror.hh"
#include "../elements/wifi/wifiseq.hh"
#include "../elements/wifi/wifidecap.hh"
#include "../elements/tcpudp/setudpchecksum.hh"
#include "../elements/ip/ipnameinfo.hh"
#include "../elements/wifi/ap/beaconsource.hh"
#include "../elements/userlevel/socket.hh"
#include "../elements/analysis/ipsumdump_udp.hh"
#include "../elements/local/rogueStaDetect.hh"
#include "../elements/userlevel/fromdump.hh"
#include "../elements/test/sorttest.hh"
#include "../elements/standard/paint.hh"
#include "../elements/standard/mixedqueue.hh"
#include "../elements/ip/ipaddrrewriter.hh"
#include "../elements/standard/strip.hh"
#include "../elements/standard/checkpaint.hh"
#include "../elements/ip/unstripipheader.hh"
#include "../elements/ip/rangeiplookup.hh"
#include "../elements/wifi/wifiencap.hh"
#include "../elements/standard/suppressor.hh"
#include "../elements/standard/messageelement.hh"
#include "../elements/ip/ipfragmenter.hh"
#include "../elements/ethernet/checkarpheader.hh"
#include "../elements/wifi/ap/openauthresponder.hh"
#include "../elements/standard/paintswitch.hh"
#include "../elements/threads/staticthreadsched.hh"
#include "../elements/standard/setpackettype.hh"
#include "../elements/standard/nullelement.hh"
#include "../elements/wifi/athdescdecap.hh"
#include "../elements/userlevel/chattersocket.hh"
#include "../elements/standard/nulls.hh"
#include <click/standard/addressinfo.hh>
#include "../elements/ip/checkipheader.hh"
#include "../elements/wifi/autoratefallback.hh"
#include "../elements/standard/shaper.hh"
#include "../elements/local/rrunqueue.hh"
#include "../elements/ethernet/arpfaker.hh"
#include "../elements/analysis/ipsumdump_link.hh"
#include "../elements/ip/storeipaddress.hh"
#include "../elements/ip/ipoutputcombo.hh"
#include "../elements/wifi/athdescencap.hh"
#include "../elements/standard/unqueue2.hh"
#include "../elements/standard/painttee.hh"
#include "../elements/wifi/prism2decap.hh"
#include "../elements/icmp/icmprewriter.hh"
#include "../elements/analysis/timefilter.hh"
#include "../elements/wifi/printtxfeedback.hh"
#include "../elements/standard/script.hh"
#include "../elements/userlevel/umlswitch.hh"
#include "../elements/test/errortest.hh"
#include "../elements/analysis/ipsumdump_icmp.hh"
#include "../elements/userlevel/tohost.hh"
#include "../elements/userlevel/khandlerproxy.hh"
#include "../elements/local/print80211.hh"
#include "../elements/analysis/eraseippayload.hh"
#include "../elements/wifi/prism2encap.hh"
#include "../elements/userlevel/controlsocket.hh"
#include "../elements/local/forceicmp.hh"
#include "../elements/analysis/aggregatelen.hh"
#include "../elements/wifi/printwifi.hh"
#include "../elements/userlevel/kernelfilter.hh"
#include "../elements/standard/classifier.hh"
#include "../elements/threads/spinlockacquire.hh"
#include "../elements/standard/ratedsplitter.hh"
#include "../elements/standard/randomerror.hh"
#include "../elements/ip/stripipheader.hh"
#include "../elements/analysis/timestampaccum.hh"
#include "../elements/userlevel/tosocket.hh"
#include "../elements/icmp/icmppingencap.hh"
#include "../elements/standard/idle.hh"
#include "../elements/ip/lookupiproute.hh"
#include "../elements/wifi/packetstore.hh"
#include "../elements/test/hashtabletest.hh"
#include "../elements/local/staTest.hh"
#include "../elements/test/checkpacket.hh"
#include "../elements/analysis/timesortedsched.hh"
#include "../elements/test/bhmtest.hh"
#include "../elements/standard/print.hh"
#include "../elements/analysis/aggregateipflows.hh"
#include "../elements/userlevel/kerneltap.hh"
#include "../elements/standard/averagecounter.hh"
#include "../elements/standard/infinitesource.hh"
#include "../elements/local/copytcpseq.hh"
#include "../elements/userlevel/fromsocket.hh"
#include "../elements/threads/spinlockinfo.hh"
#include "../elements/test/upstreamnotifier.hh"
#include <click/standard/scheduleinfo.hh>
#include "../elements/standard/counter.hh"
#include "../elements/ip/rripmapper.hh"
#include "../elements/ethernet/arpquerier.hh"
#include "../elements/tcpudp/tcpipsend.hh"
#include "../elements/standard/fullnotequeue.hh"
#include "../elements/analysis/ipsumdumpinfo.hh"
#include "../elements/standard/notifierqueue.hh"
#include "../elements/standard/checkcrc32.hh"
#include "../elements/local/tcpack.hh"
#include "../elements/ip/lineariplookup.hh"
#include "../elements/standard/randomswitch.hh"
#include "../elements/ip/setrandipaddress.hh"
#include "../elements/analysis/aggcounter.hh"
#include "../elements/analysis/timerange.hh"
#include "../elements/wifi/rxstats.hh"
#include "../elements/analysis/storetimestamp.hh"
#include "../elements/tcpudp/checktcpheader.hh"
#include "../elements/local/rogueDetect.hh"
#include "../elements/ip/setipaddress.hh"
#include "../elements/wifi/station/openauthrequester.hh"
#include "../elements/test/neighborhoodtest.hh"
#include "../elements/standard/discardnofree.hh"
#include "../elements/ethernet/arptable.hh"
#include "../elements/test/queueyanktest.hh"
#include "../elements/tcpudp/dynudpipencap.hh"
#include "../elements/standard/unstrip.hh"
#include "../elements/standard/discard.hh"
#include "../elements/standard/priosched.hh"
#include "../elements/standard/checklength.hh"
#include "../elements/standard/align.hh"
#include "../elements/test/schedordertest.hh"
#include "../elements/tcpudp/checkudpheader.hh"
#include "../elements/ethernet/etherencap.hh"
#include "../elements/analysis/aggregatepaint.hh"
#include "../elements/ip/checkipheader2.hh"
#include "../elements/wifi/probetxrate.hh"
#include "../elements/standard/drr.hh"
#include "../elements/ip/ipfilter.hh"
#include "../elements/wifi/wirelessinfo.hh"
#include "../elements/tcpudp/tcprewriter.hh"
#include "../elements/local/tcpbuffer.hh"
#include "../elements/ethernet/arpprint.hh"
#include "../elements/standard/strideswitch.hh"
#include "../elements/ip/sortediplookup.hh"
#include "../elements/wifi/radiotapdecap.hh"
#include "../elements/ethernet/storeetheraddress.hh"
#include "../elements/analysis/aggregateipaddrpair.hh"
#include "../elements/standard/randomsource.hh"
#include "../elements/analysis/toipflowdumps.hh"
#include "../elements/aqm/adaptivered.hh"
#include "../elements/wifi/filterfailures.hh"
#include "../elements/standard/pokehandlers.hh"
#include "../elements/userlevel/todevice.hh"
#include <click/standard/portinfo.hh>
#include "../elements/wifi/radiotapencap.hh"
#include "../elements/standard/unqueue.hh"
#include "../elements/standard/truncate.hh"
#include "../elements/standard/pullswitch.hh"
#include "../elements/analysis/fromtcpdump.hh"
#include "../elements/test/heaptest.hh"
#include "../elements/tcpudp/iprewriter.hh"
#include "../elements/wifi/wifidupefilter.hh"
#include "../elements/userlevel/progressbar.hh"
#include "../elements/userlevel/fromrawsocket.hh"
#include "../elements/ip/markipheader.hh"
#include "../elements/userlevel/rawsocket.hh"
#include "../elements/userlevel/fromhost.hh"
#include "../elements/test/confparsetest.hh"
#include "../elements/standard/timedsink.hh"
#include "../elements/standard/setcrc32.hh"
#include "../elements/standard/compblock.hh"
#include "../elements/standard/bandwidthshaper.hh"
#include "../elements/ip/ripsend.hh"
#include "../elements/test/notifierdebug.hh"
#include "../elements/tcpudp/udpipencap.hh"
#include "../elements/standard/setannobyte.hh"
#include "../elements/analysis/fromdagdump.hh"
#include "../elements/standard/quitwatcher.hh"
#include "../elements/ip/setipdscp.hh"
#include "../elements/ethernet/arpresponder.hh"
#include "../elements/userlevel/fromdevice.hh"
#include "../elements/analysis/ipsumdump_payload.hh"
#include "../elements/standard/hashswitch.hh"
#include "../elements/standard/block.hh"
#include "../elements/standard/rrswitch.hh"
#include "../elements/ip/ipratemon.hh"
#include "../elements/ethernet/ensureether.hh"
#include "../elements/userlevel/kerneltun.hh"
#include "../elements/local/printairo.hh"
#include "../elements/analysis/fromnlanrdump.hh"
#include "../elements/analysis/aggregatefilter.hh"
#include "../elements/wifi/ap/stationtable.hh"
#include "../elements/wifi/ap/proberesponder.hh"
#include "../elements/userlevel/torawsocket.hh"
#include "../elements/test/packettest.hh"
#include "../elements/standard/stridesched.hh"
#include "../elements/local/tcpdemux.hh"
#include "../elements/ip/iprwpatterns.hh"
CLICK_USING_DECLS
static Element *
beetlemonkey(uintptr_t heywood)
{
  switch (heywood) {
   case 0: return new AggregateCounter;
   case 1: return new AggregatePacketCounter;
   case 2: return new AggregateFilter;
   case 3: return new AggregateFirst;
   case 4: return new AggregateIPAddrPair;
   case 5: return new AggregateIP;
   case 6: return new AggregateIPFlows;
   case 7: return new AggregateLast;
   case 8: return new AggregateLength;
   case 9: return new AggregatePaint;
   case 10: return new AnonymizeIPAddr;
   case 11: return new EraseIPPayload;
   case 12: return new FromCapDump;
   case 13: return new FromDAGDump;
   case 14: return new FromIPSummaryDump;
   case 15: return new FromNetFlowSummaryDump;
   case 16: return new FromNLANRDump;
   case 17: return new FromTcpdump;
   case 18: return new SetTimestampDelta;
   case 19: return new StoreTimestamp;
   case 20: return new TimeFilter;
   case 21: return new TimeRange;
   case 22: return new TimeSortedSched;
   case 23: return new TimestampAccum;
   case 24: return new ToIPFlowDumps;
   case 25: return new ToIPSummaryDump;
   case 26: return new FTPPortMapper;
   case 27: return new AdaptiveRED;
   case 28: return new RED;
   case 29: return new ARPFaker;
   case 30: return new ARPPrint;
   case 31: return new ARPQuerier;
   case 32: return new ARPResponder;
   case 33: return new ARPTable;
   case 34: return new CheckARPHeader;
   case 35: return new EnsureEther;
   case 36: return new EtherEncap;
   case 37: return new EtherMirror;
   case 38: return new EtherPauseSource;
   case 39: return new HostEtherFilter;
   case 40: return new StoreEtherAddress;
   case 41: return new CheckICMPHeader;
   case 42: return new ICMPError;
   case 43: return new ICMPPingEncap;
   case 44: return new ICMPPingResponder;
   case 45: return new ICMPPingRewriter;
   case 46: return new ICMPRewriter;
   case 47: return new ICMPPingSource;
   case 48: return new ICMPPingSource;
   case 49: return new CheckIPHeader2;
   case 50: return new CheckIPHeader;
   case 51: return new DecIPTTL;
   case 52: return new DirectIPLookup;
   case 53: return new FixIPSrc;
   case 54: return new GetIPAddress;
   case 55: return new IPAddrPairRewriter;
   case 56: return new IPAddrRewriter;
   case 57: return new IPClassifier;
   case 58: return new IPEncap;
   case 59: return new IPFieldInfo;
   case 60: return new IPFilter;
   case 61: return new IPFragmenter;
   case 62: return new IPGWOptions;
   case 63: return new IPInputCombo;
   case 64: return new IPMirror;
   case 65: return new IPNameInfo;
   case 66: return new IPOutputCombo;
   case 67: return new IPPrint;
   case 68: return new IPRateMonitor;
   case 69: return new IPReassembler;
   case 70: return new IPRewriterPatterns;
   case 71: return new LinearIPLookup;
   case 72: return new StaticIPLookup;
   case 73: return new LinuxIPLookup;
   case 74: return new MarkIPCE;
   case 75: return new MarkIPHeader;
   case 76: return new RadixIPLookup;
   case 77: return new RangeIPLookup;
   case 78: return new RFC2507c;
   case 79: return new RFC2507d;
   case 80: return new RIPSend;
   case 81: return new RoundRobinIPMapper;
   case 82: return new SetIPAddress;
   case 83: return new SetIPChecksum;
   case 84: return new SetIPDSCP;
   case 85: return new SetRandIPAddress;
   case 86: return new SourceIPHashMapper;
   case 87: return new SortedIPLookup;
   case 88: return new StoreIPAddress;
   case 89: return new StripIPHeader;
   case 90: return new TruncateIPPayload;
   case 91: return new UnstripIPHeader;
   case 92: return new Basic;
   case 93: return new BufferConverter;
   case 94: return new CopyFlowID;
   case 95: return new CopyTCPSeq;
   case 96: return new DupPath;
   case 97: return new ForceICMP;
   case 98: return new ForceIP;
   case 99: return new ForceTCP;
   case 100: return new ForceUDP;
   case 101: return new Pad;
   case 102: return new Print80211;
   case 103: return new PrintAiro;
   case 104: return new Reframe;
   case 105: return new RogueDetect;
   case 106: return new RogueStaDetect;
   case 107: return new RoundRobinUnqueue;
   case 108: return new StaTest;
   case 109: return new TCPAck;
   case 110: return new TCPBuffer;
   case 111: return new TCPConn;
   case 112: return new TCPDemux;
   case 113: return new TCPReflector;
   case 114: return new ToyTCP;
   case 115: return new WebGen;
   case 116: return new AddressInfo;
   case 117: return new Align;
   case 118: return new AlignmentInfo;
   case 119: return new AnnotationInfo;
   case 120: return new AverageCounter;
   case 121: return new BandwidthMeter;
   case 122: return new BandwidthShaper;
   case 123: return new Block;
   case 124: return new Burster;
   case 125: return new BandwidthRatedSplitter;
   case 126: return new BandwidthRatedUnqueue;
   case 127: return new CheckCRC32;
   case 128: return new CheckLength;
   case 129: return new CheckPaint;
   case 130: return new Classifier;
   case 131: return new CompareBlock;
   case 132: return new Counter;
   case 133: return new DelayShaper;
   case 134: return new DelayUnqueue;
   case 135: return new DevirtualizeInfo;
   case 136: return new Discard;
   case 137: return new DiscardNoFree;
   case 138: return new DriverManager;
   case 139: return new DropBroadcasts;
   case 140: return new DRRSched;
   case 141: return new ErrorElement;
   case 142: return new FlowInfo;
   case 143: return new FrontDropQueue;
   case 144: return new FullNoteQueue;
   case 145: return new FullNoteQueue;
   case 146: return new HashSwitch;
   case 147: return new Hub;
   case 148: return new Idle;
   case 149: return new InfiniteSource;
   case 150: return new LinkUnqueue;
   case 151: return new MessageElement;
   case 152: return new Meter;
   case 153: return new MixedQueue;
   case 154: return new NotifierQueue;
   case 155: return new NullElement;
   case 156: return new PushNullElement;
   case 157: return new PullNullElement;
   case 158: return new Null4;
   case 159: return new Null5;
   case 160: return new Null6;
   case 161: return new Null7;
   case 162: return new Null8;
   case 163: return new Null1;
   case 164: return new Null2;
   case 165: return new Null3;
   case 166: return new Paint;
   case 167: return new PaintSwitch;
   case 168: return new PaintTee;
   case 169: return new PokeHandlers;
   case 170: return new PortInfo;
   case 171: return new Print;
   case 172: return new PrioSched;
   case 173: return new PullSwitch;
   case 174: return new QuickNoteQueue;
   case 175: return new QuitWatcher;
   case 176: return new RandomBitErrors;
   case 177: return new RandomSample;
   case 178: return new RandomSource;
   case 179: return new RandomSwitch;
   case 180: return new RatedSource;
   case 181: return new RatedSplitter;
   case 182: return new RatedUnqueue;
   case 183: return new RRSched;
   case 184: return new RoundRobinSwitch;
   case 185: return new ScheduleInfo;
   case 186: return new Script;
   case 187: return new SetAnnoByte;
   case 188: return new SetCRC32;
   case 189: return new SetPacketType;
   case 190: return new SetTimestamp;
   case 191: return new Shaper;
   case 192: return new SimpleQueue;
   case 193: return new StaticPullSwitch;
   case 194: return new StaticSwitch;
   case 195: return new StoreData;
   case 196: return new StrideSched;
   case 197: return new StrideSwitch;
   case 198: return new Strip;
   case 199: return new StripToNetworkHeader;
   case 200: return new Suppressor;
   case 201: return new Switch;
   case 202: return new Tee;
   case 203: return new PullTee;
   case 204: return new ThreadSafeQueue;
   case 205: return new TimedSink;
   case 206: return new TimedSource;
   case 207: return new TimedUnqueue;
   case 208: return new Truncate;
   case 209: return new Unqueue2;
   case 210: return new Unqueue;
   case 211: return new Unstrip;
   case 212: return new CheckTCPHeader;
   case 213: return new CheckUDPHeader;
   case 214: return new DynamicUDPIPEncap;
   case 215: return new IPRewriter;
   case 216: return new SetTCPChecksum;
   case 217: return new SetUDPChecksum;
   case 218: return new TCPIPSend;
   case 219: return new TCPRewriter;
   case 220: return new UDPIPEncap;
   case 221: return new BigHashMapTest;
   case 222: return new BigintTest;
   case 223: return new CheckPacket;
   case 224: return new CLPTest;
   case 225: return new ComparePackets;
   case 226: return new ConfParseTest;
   case 227: return new ErrorTest;
   case 228: return new FunctionTest;
   case 229: return new HashTableTest;
   case 230: return new HeapTest;
   case 231: return new ListTest;
   case 232: return new NeighborhoodTest;
   case 233: return new NotifierDebug;
   case 234: return new PacketTest;
   case 235: return new QueueYankTest;
   case 236: return new RandomSeed;
   case 237: return new SchedOrderTest;
   case 238: return new SortTest;
   case 239: return new UpstreamNotifier;
   case 240: return new VectorTest;
   case 241: return new SpinlockAcquire;
   case 242: return new SpinlockInfo;
   case 243: return new SpinlockRelease;
   case 244: return new StaticThreadSched;
   case 245: return new ChangeUID;
   case 246: return new ChatterSocket;
   case 247: return new ControlSocket;
   case 248: return new FromDevice;
   case 249: return new FromDump;
   case 250: return new FromHost;
   case 251: return new FromRawSocket;
   case 252: return new FromSocket;
   case 253: return new KernelFilter;
   case 254: return new KernelTap;
   case 255: return new KernelTun;
   case 256: return new KernelHandlerProxy;
   case 257: return new ProgressBar;
   case 258: return new RawSocket;
   case 259: return new Socket;
   case 260: return new ToDevice;
   case 261: return new ToDump;
   case 262: return new ToHost;
   case 263: return new ToRawSocket;
   case 264: return new ToSocket;
   case 265: return new UMLSwitch;
   case 266: return new AssociationResponder;
   case 267: return new BeaconSource;
   case 268: return new OpenAuthResponder;
   case 269: return new ProbeResponder;
   case 270: return new StationTable;
   case 271: return new AthdescDecap;
   case 272: return new AthdescEncap;
   case 273: return new AutoRateFallback;
   case 274: return new AvailableRates;
   case 275: return new EtherCount;
   case 276: return new ExtraDecap;
   case 277: return new ExtraEncap;
   case 278: return new FilterFailures;
   case 279: return new FilterPhyErr;
   case 280: return new FilterTX;
   case 281: return new FromHandler;
   case 282: return new LinkTable;
   case 283: return new MadwifiRate;
   case 284: return new PacketStore;
   case 285: return new PrintTXFeedback;
   case 286: return new PrintWifi;
   case 287: return new Prism2Decap;
   case 288: return new Prism2Encap;
   case 289: return new ProbeTXRate;
   case 290: return new PushAnno;
   case 291: return new RadiotapDecap;
   case 292: return new RadiotapEncap;
   case 293: return new ReadAnno;
   case 294: return new RXStats;
   case 295: return new SetTXPower;
   case 296: return new SetTXRate;
   case 297: return new AssociationRequester;
   case 298: return new BeaconScanner;
   case 299: return new BeaconTracker;
   case 300: return new OpenAuthRequester;
   case 301: return new ProbeRequester;
   case 302: return new WepDecap;
   case 303: return new WepEncap;
   case 304: return new WifiDecap;
   case 305: return new WifiDefrag;
   case 306: return new WifiDupeFilter;
   case 307: return new WifiEncap;
   case 308: return new WifiFragment;
   case 309: return new WifiSeq;
   case 310: return new WirelessInfo;
   default: return 0;
  }
}

#ifdef CLICK_LINUXMODULE
#define click_add_element_type(n, f, t) click_add_element_type((n), (f), (t), 0)
#endif
void
click_export_elements()
{
  (void) click_add_element_type("AggregateCounter", beetlemonkey, 0);
  (void) click_add_element_type("AggregatePacketCounter", beetlemonkey, 1);
  (void) click_add_element_type("AggregateFilter", beetlemonkey, 2);
  (void) click_add_element_type("AggregateFirst", beetlemonkey, 3);
  (void) click_add_element_type("AggregateIPAddrPair", beetlemonkey, 4);
  (void) click_add_element_type("AggregateIP", beetlemonkey, 5);
  (void) click_add_element_type("AggregateIPFlows", beetlemonkey, 6);
  (void) click_add_element_type("AggregateLast", beetlemonkey, 7);
  (void) click_add_element_type("AggregateLength", beetlemonkey, 8);
  (void) click_add_element_type("AggregatePaint", beetlemonkey, 9);
  (void) click_add_element_type("AnonymizeIPAddr", beetlemonkey, 10);
  (void) click_add_element_type("EraseIPPayload", beetlemonkey, 11);
  (void) click_add_element_type("FromCapDump", beetlemonkey, 12);
  (void) click_add_element_type("FromDAGDump", beetlemonkey, 13);
  (void) click_add_element_type("FromIPSummaryDump", beetlemonkey, 14);
  (void) click_add_element_type("FromNetFlowSummaryDump", beetlemonkey, 15);
  (void) click_add_element_type("FromNLANRDump", beetlemonkey, 16);
  (void) click_add_element_type("FromTcpdump", beetlemonkey, 17);
  IPSummaryDump_Anno::static_initialize();
  IPSummaryDump_ICMP::static_initialize();
  IPSummaryDump_IP::static_initialize();
  IPSummaryDump_Link::static_initialize();
  IPSummaryDump_Payload::static_initialize();
  IPSummaryDump_TCP::static_initialize();
  IPSummaryDump_UDP::static_initialize();
  (void) click_add_element_type("SetTimestampDelta", beetlemonkey, 18);
  (void) click_add_element_type("StoreTimestamp", beetlemonkey, 19);
  (void) click_add_element_type("TimeFilter", beetlemonkey, 20);
  (void) click_add_element_type("TimeRange", beetlemonkey, 21);
  (void) click_add_element_type("TimeSortedSched", beetlemonkey, 22);
  (void) click_add_element_type("TimestampAccum", beetlemonkey, 23);
  (void) click_add_element_type("ToIPFlowDumps", beetlemonkey, 24);
  (void) click_add_element_type("ToIPSummaryDump", beetlemonkey, 25);
  (void) click_add_element_type("FTPPortMapper", beetlemonkey, 26);
  (void) click_add_element_type("AdaptiveRED", beetlemonkey, 27);
  (void) click_add_element_type("RED", beetlemonkey, 28);
  (void) click_add_element_type("ARPFaker", beetlemonkey, 29);
  (void) click_add_element_type("ARPPrint", beetlemonkey, 30);
  (void) click_add_element_type("ARPQuerier", beetlemonkey, 31);
  (void) click_add_element_type("ARPResponder", beetlemonkey, 32);
  (void) click_add_element_type("ARPTable", beetlemonkey, 33);
  (void) click_add_element_type("CheckARPHeader", beetlemonkey, 34);
  (void) click_add_element_type("EnsureEther", beetlemonkey, 35);
  (void) click_add_element_type("EtherEncap", beetlemonkey, 36);
  (void) click_add_element_type("EtherMirror", beetlemonkey, 37);
  (void) click_add_element_type("EtherPauseSource", beetlemonkey, 38);
  (void) click_add_element_type("HostEtherFilter", beetlemonkey, 39);
  (void) click_add_element_type("StoreEtherAddress", beetlemonkey, 40);
  (void) click_add_element_type("CheckICMPHeader", beetlemonkey, 41);
  (void) click_add_element_type("ICMPError", beetlemonkey, 42);
  (void) click_add_element_type("ICMPPingEncap", beetlemonkey, 43);
  (void) click_add_element_type("ICMPPingResponder", beetlemonkey, 44);
  (void) click_add_element_type("ICMPPingRewriter", beetlemonkey, 45);
  (void) click_add_element_type("ICMPRewriter", beetlemonkey, 46);
  (void) click_add_element_type("ICMPPingSource", beetlemonkey, 47);
  (void) click_add_element_type("ICMPSendPings", beetlemonkey, 48);
  (void) click_add_element_type("CheckIPHeader2", beetlemonkey, 49);
  (void) click_add_element_type("CheckIPHeader", beetlemonkey, 50);
  CheckIPHeader::static_initialize();
  (void) click_add_element_type("DecIPTTL", beetlemonkey, 51);
  (void) click_add_element_type("DirectIPLookup", beetlemonkey, 52);
  (void) click_add_element_type("FixIPSrc", beetlemonkey, 53);
  (void) click_add_element_type("GetIPAddress", beetlemonkey, 54);
  (void) click_add_element_type("IPAddrPairRewriter", beetlemonkey, 55);
  (void) click_add_element_type("IPAddrRewriter", beetlemonkey, 56);
  (void) click_add_element_type("IPClassifier", beetlemonkey, 57);
  (void) click_add_element_type("IPEncap", beetlemonkey, 58);
  (void) click_add_element_type("IPFieldInfo", beetlemonkey, 59);
  IPFieldInfo::static_initialize();
  (void) click_add_element_type("IPFilter", beetlemonkey, 60);
  IPFilter::static_initialize();
  (void) click_add_element_type("IPFragmenter", beetlemonkey, 61);
  (void) click_add_element_type("IPGWOptions", beetlemonkey, 62);
  (void) click_add_element_type("IPInputCombo", beetlemonkey, 63);
  (void) click_add_element_type("IPMirror", beetlemonkey, 64);
  (void) click_add_element_type("IPNameInfo", beetlemonkey, 65);
  IPNameInfo::static_initialize();
  (void) click_add_element_type("IPOutputCombo", beetlemonkey, 66);
  (void) click_add_element_type("IPPrint", beetlemonkey, 67);
  (void) click_add_element_type("IPRateMonitor", beetlemonkey, 68);
  (void) click_add_element_type("IPReassembler", beetlemonkey, 69);
  (void) click_add_element_type("IPRewriterPatterns", beetlemonkey, 70);
  (void) click_add_element_type("LinearIPLookup", beetlemonkey, 71);
  (void) click_add_element_type("StaticIPLookup", beetlemonkey, 72);
  (void) click_add_element_type("LinuxIPLookup", beetlemonkey, 73);
  (void) click_add_element_type("MarkIPCE", beetlemonkey, 74);
  (void) click_add_element_type("MarkIPHeader", beetlemonkey, 75);
  (void) click_add_element_type("RadixIPLookup", beetlemonkey, 76);
  (void) click_add_element_type("RangeIPLookup", beetlemonkey, 77);
  (void) click_add_element_type("RFC2507Comp", beetlemonkey, 78);
  (void) click_add_element_type("RFC2507Decomp", beetlemonkey, 79);
  (void) click_add_element_type("RIPSend", beetlemonkey, 80);
  (void) click_add_element_type("RoundRobinIPMapper", beetlemonkey, 81);
  (void) click_add_element_type("SetIPAddress", beetlemonkey, 82);
  (void) click_add_element_type("SetIPChecksum", beetlemonkey, 83);
  (void) click_add_element_type("SetIPDSCP", beetlemonkey, 84);
  (void) click_add_element_type("SetRandIPAddress", beetlemonkey, 85);
  (void) click_add_element_type("SourceIPHashMapper", beetlemonkey, 86);
  (void) click_add_element_type("SortedIPLookup", beetlemonkey, 87);
  (void) click_add_element_type("StoreIPAddress", beetlemonkey, 88);
  (void) click_add_element_type("StripIPHeader", beetlemonkey, 89);
  (void) click_add_element_type("TruncateIPPayload", beetlemonkey, 90);
  (void) click_add_element_type("UnstripIPHeader", beetlemonkey, 91);
  (void) click_add_element_type("Basic", beetlemonkey, 92);
  (void) click_add_element_type("BufferConverter", beetlemonkey, 93);
  (void) click_add_element_type("CopyFlowID", beetlemonkey, 94);
  (void) click_add_element_type("CopyTCPSeq", beetlemonkey, 95);
  (void) click_add_element_type("DupPath", beetlemonkey, 96);
  (void) click_add_element_type("ForceICMP", beetlemonkey, 97);
  (void) click_add_element_type("ForceIP", beetlemonkey, 98);
  (void) click_add_element_type("ForceTCP", beetlemonkey, 99);
  (void) click_add_element_type("ForceUDP", beetlemonkey, 100);
  (void) click_add_element_type("Pad", beetlemonkey, 101);
  (void) click_add_element_type("Print80211", beetlemonkey, 102);
  (void) click_add_element_type("PrintAiro", beetlemonkey, 103);
  (void) click_add_element_type("Reframe", beetlemonkey, 104);
  (void) click_add_element_type("RogueDetect", beetlemonkey, 105);
  (void) click_add_element_type("RogueStaDetect", beetlemonkey, 106);
  (void) click_add_element_type("RoundRobinUnqueue", beetlemonkey, 107);
  (void) click_add_element_type("StaTest", beetlemonkey, 108);
  (void) click_add_element_type("TCPAck", beetlemonkey, 109);
  (void) click_add_element_type("TCPBuffer", beetlemonkey, 110);
  (void) click_add_element_type("TCPConn", beetlemonkey, 111);
  (void) click_add_element_type("TCPDemux", beetlemonkey, 112);
  (void) click_add_element_type("TCPReflector", beetlemonkey, 113);
  (void) click_add_element_type("ToyTCP", beetlemonkey, 114);
  (void) click_add_element_type("WebGen", beetlemonkey, 115);
  (void) click_add_element_type("AddressInfo", beetlemonkey, 116);
  (void) click_add_element_type("Align", beetlemonkey, 117);
  (void) click_add_element_type("AlignmentInfo", beetlemonkey, 118);
  (void) click_add_element_type("AnnotationInfo", beetlemonkey, 119);
  (void) click_add_element_type("AverageCounter", beetlemonkey, 120);
  (void) click_add_element_type("BandwidthMeter", beetlemonkey, 121);
  (void) click_add_element_type("BandwidthShaper", beetlemonkey, 122);
  (void) click_add_element_type("Block", beetlemonkey, 123);
  (void) click_add_element_type("Burster", beetlemonkey, 124);
  (void) click_add_element_type("BandwidthRatedSplitter", beetlemonkey, 125);
  (void) click_add_element_type("BandwidthRatedUnqueue", beetlemonkey, 126);
  (void) click_add_element_type("CheckCRC32", beetlemonkey, 127);
  (void) click_add_element_type("CheckLength", beetlemonkey, 128);
  (void) click_add_element_type("CheckPaint", beetlemonkey, 129);
  (void) click_add_element_type("Classifier", beetlemonkey, 130);
  (void) click_add_element_type("CompareBlock", beetlemonkey, 131);
  (void) click_add_element_type("Counter", beetlemonkey, 132);
  (void) click_add_element_type("DelayShaper", beetlemonkey, 133);
  (void) click_add_element_type("DelayUnqueue", beetlemonkey, 134);
  (void) click_add_element_type("DevirtualizeInfo", beetlemonkey, 135);
  (void) click_add_element_type("Discard", beetlemonkey, 136);
  (void) click_add_element_type("DiscardNoFree", beetlemonkey, 137);
  (void) click_add_element_type("DriverManager", beetlemonkey, 138);
  (void) click_add_element_type("DropBroadcasts", beetlemonkey, 139);
  (void) click_add_element_type("DRRSched", beetlemonkey, 140);
  (void) click_add_element_type("ErrorElement", beetlemonkey, 141);
  (void) click_add_element_type("FlowInfo", beetlemonkey, 142);
  (void) click_add_element_type("FrontDropQueue", beetlemonkey, 143);
  (void) click_add_element_type("Queue", beetlemonkey, 144);
  (void) click_add_element_type("FullNoteQueue", beetlemonkey, 145);
  (void) click_add_element_type("HashSwitch", beetlemonkey, 146);
  (void) click_add_element_type("Hub", beetlemonkey, 147);
  (void) click_add_element_type("Idle", beetlemonkey, 148);
  (void) click_add_element_type("InfiniteSource", beetlemonkey, 149);
  (void) click_add_element_type("LinkUnqueue", beetlemonkey, 150);
  (void) click_add_element_type("Message", beetlemonkey, 151);
  (void) click_add_element_type("Meter", beetlemonkey, 152);
  (void) click_add_element_type("MixedQueue", beetlemonkey, 153);
  (void) click_add_element_type("NotifierQueue", beetlemonkey, 154);
  (void) click_add_element_type("Null", beetlemonkey, 155);
  (void) click_add_element_type("PushNull", beetlemonkey, 156);
  (void) click_add_element_type("PullNull", beetlemonkey, 157);
  (void) click_add_element_type("Null4", beetlemonkey, 158);
  (void) click_add_element_type("Null5", beetlemonkey, 159);
  (void) click_add_element_type("Null6", beetlemonkey, 160);
  (void) click_add_element_type("Null7", beetlemonkey, 161);
  (void) click_add_element_type("Null8", beetlemonkey, 162);
  (void) click_add_element_type("Null1", beetlemonkey, 163);
  (void) click_add_element_type("Null2", beetlemonkey, 164);
  (void) click_add_element_type("Null3", beetlemonkey, 165);
  (void) click_add_element_type("Paint", beetlemonkey, 166);
  (void) click_add_element_type("PaintSwitch", beetlemonkey, 167);
  (void) click_add_element_type("PaintTee", beetlemonkey, 168);
  (void) click_add_element_type("PokeHandlers", beetlemonkey, 169);
  (void) click_add_element_type("PortInfo", beetlemonkey, 170);
  (void) click_add_element_type("Print", beetlemonkey, 171);
  (void) click_add_element_type("PrioSched", beetlemonkey, 172);
  (void) click_add_element_type("PullSwitch", beetlemonkey, 173);
  (void) click_add_element_type("QuickNoteQueue", beetlemonkey, 174);
  (void) click_add_element_type("QuitWatcher", beetlemonkey, 175);
  (void) click_add_element_type("RandomBitErrors", beetlemonkey, 176);
  (void) click_add_element_type("RandomSample", beetlemonkey, 177);
  (void) click_add_element_type("RandomSource", beetlemonkey, 178);
  (void) click_add_element_type("RandomSwitch", beetlemonkey, 179);
  (void) click_add_element_type("RatedSource", beetlemonkey, 180);
  (void) click_add_element_type("RatedSplitter", beetlemonkey, 181);
  (void) click_add_element_type("RatedUnqueue", beetlemonkey, 182);
  (void) click_add_element_type("RoundRobinSched", beetlemonkey, 183);
  (void) click_add_element_type("RoundRobinSwitch", beetlemonkey, 184);
  (void) click_add_element_type("ScheduleInfo", beetlemonkey, 185);
  (void) click_add_element_type("Script", beetlemonkey, 186);
  Script::static_initialize();
  (void) click_add_element_type("SetAnnoByte", beetlemonkey, 187);
  (void) click_add_element_type("SetCRC32", beetlemonkey, 188);
  (void) click_add_element_type("SetPacketType", beetlemonkey, 189);
  (void) click_add_element_type("SetTimestamp", beetlemonkey, 190);
  (void) click_add_element_type("Shaper", beetlemonkey, 191);
  (void) click_add_element_type("SimpleQueue", beetlemonkey, 192);
  (void) click_add_element_type("StaticPullSwitch", beetlemonkey, 193);
  (void) click_add_element_type("StaticSwitch", beetlemonkey, 194);
  (void) click_add_element_type("StoreData", beetlemonkey, 195);
  (void) click_add_element_type("StrideSched", beetlemonkey, 196);
  (void) click_add_element_type("StrideSwitch", beetlemonkey, 197);
  (void) click_add_element_type("Strip", beetlemonkey, 198);
  (void) click_add_element_type("StripToNetworkHeader", beetlemonkey, 199);
  (void) click_add_element_type("Suppressor", beetlemonkey, 200);
  (void) click_add_element_type("Switch", beetlemonkey, 201);
  (void) click_add_element_type("Tee", beetlemonkey, 202);
  (void) click_add_element_type("PullTee", beetlemonkey, 203);
  (void) click_add_element_type("ThreadSafeQueue", beetlemonkey, 204);
  (void) click_add_element_type("TimedSink", beetlemonkey, 205);
  (void) click_add_element_type("TimedSource", beetlemonkey, 206);
  (void) click_add_element_type("TimedUnqueue", beetlemonkey, 207);
  (void) click_add_element_type("Truncate", beetlemonkey, 208);
  (void) click_add_element_type("Unqueue2", beetlemonkey, 209);
  (void) click_add_element_type("Unqueue", beetlemonkey, 210);
  (void) click_add_element_type("Unstrip", beetlemonkey, 211);
  (void) click_add_element_type("CheckTCPHeader", beetlemonkey, 212);
  (void) click_add_element_type("CheckUDPHeader", beetlemonkey, 213);
  (void) click_add_element_type("DynamicUDPIPEncap", beetlemonkey, 214);
  (void) click_add_element_type("IPRewriter", beetlemonkey, 215);
  (void) click_add_element_type("SetTCPChecksum", beetlemonkey, 216);
  (void) click_add_element_type("SetUDPChecksum", beetlemonkey, 217);
  (void) click_add_element_type("TCPIPSend", beetlemonkey, 218);
  (void) click_add_element_type("TCPRewriter", beetlemonkey, 219);
  (void) click_add_element_type("UDPIPEncap", beetlemonkey, 220);
  (void) click_add_element_type("BigHashMapTest", beetlemonkey, 221);
  (void) click_add_element_type("BigintTest", beetlemonkey, 222);
  (void) click_add_element_type("CheckPacket", beetlemonkey, 223);
  (void) click_add_element_type("CLPTest", beetlemonkey, 224);
  (void) click_add_element_type("ComparePackets", beetlemonkey, 225);
  (void) click_add_element_type("ConfParseTest", beetlemonkey, 226);
  (void) click_add_element_type("ErrorTest", beetlemonkey, 227);
  (void) click_add_element_type("FunctionTest", beetlemonkey, 228);
  (void) click_add_element_type("HashTableTest", beetlemonkey, 229);
  (void) click_add_element_type("HeapTest", beetlemonkey, 230);
  (void) click_add_element_type("ListTest", beetlemonkey, 231);
  (void) click_add_element_type("NeighborhoodTest", beetlemonkey, 232);
  (void) click_add_element_type("NotifierDebug", beetlemonkey, 233);
  (void) click_add_element_type("PacketTest", beetlemonkey, 234);
  (void) click_add_element_type("QueueYankTest", beetlemonkey, 235);
  (void) click_add_element_type("RandomSeed", beetlemonkey, 236);
  (void) click_add_element_type("SchedOrderTest", beetlemonkey, 237);
  (void) click_add_element_type("SortTest", beetlemonkey, 238);
  (void) click_add_element_type("UpstreamNotifier", beetlemonkey, 239);
  (void) click_add_element_type("VectorTest", beetlemonkey, 240);
  (void) click_add_element_type("SpinlockAcquire", beetlemonkey, 241);
  (void) click_add_element_type("SpinlockInfo", beetlemonkey, 242);
  (void) click_add_element_type("SpinlockRelease", beetlemonkey, 243);
  (void) click_add_element_type("StaticThreadSched", beetlemonkey, 244);
  (void) click_add_element_type("ChangeUID", beetlemonkey, 245);
  (void) click_add_element_type("ChatterSocket", beetlemonkey, 246);
  (void) click_add_element_type("ControlSocket", beetlemonkey, 247);
  (void) click_add_element_type("FromDevice", beetlemonkey, 248);
  (void) click_add_element_type("FromDump", beetlemonkey, 249);
  (void) click_add_element_type("FromHost", beetlemonkey, 250);
  (void) click_add_element_type("FromRawSocket", beetlemonkey, 251);
  (void) click_add_element_type("FromSocket", beetlemonkey, 252);
  (void) click_add_element_type("KernelFilter", beetlemonkey, 253);
  (void) click_add_element_type("KernelTap", beetlemonkey, 254);
  (void) click_add_element_type("KernelTun", beetlemonkey, 255);
  (void) click_add_element_type("KernelHandlerProxy", beetlemonkey, 256);
  (void) click_add_element_type("ProgressBar", beetlemonkey, 257);
  (void) click_add_element_type("RawSocket", beetlemonkey, 258);
  (void) click_add_element_type("Socket", beetlemonkey, 259);
  (void) click_add_element_type("ToDevice", beetlemonkey, 260);
  (void) click_add_element_type("ToDump", beetlemonkey, 261);
  (void) click_add_element_type("ToHost", beetlemonkey, 262);
  (void) click_add_element_type("ToRawSocket", beetlemonkey, 263);
  (void) click_add_element_type("ToSocket", beetlemonkey, 264);
  (void) click_add_element_type("UMLSwitch", beetlemonkey, 265);
  (void) click_add_element_type("AssociationResponder", beetlemonkey, 266);
  (void) click_add_element_type("BeaconSource", beetlemonkey, 267);
  (void) click_add_element_type("OpenAuthResponder", beetlemonkey, 268);
  (void) click_add_element_type("ProbeResponder", beetlemonkey, 269);
  (void) click_add_element_type("StationTable", beetlemonkey, 270);
  (void) click_add_element_type("AthdescDecap", beetlemonkey, 271);
  (void) click_add_element_type("AthdescEncap", beetlemonkey, 272);
  (void) click_add_element_type("AutoRateFallback", beetlemonkey, 273);
  (void) click_add_element_type("AvailableRates", beetlemonkey, 274);
  (void) click_add_element_type("EtherCount", beetlemonkey, 275);
  (void) click_add_element_type("ExtraDecap", beetlemonkey, 276);
  (void) click_add_element_type("ExtraEncap", beetlemonkey, 277);
  (void) click_add_element_type("FilterFailures", beetlemonkey, 278);
  (void) click_add_element_type("FilterPhyErr", beetlemonkey, 279);
  (void) click_add_element_type("FilterTX", beetlemonkey, 280);
  (void) click_add_element_type("FromHandler", beetlemonkey, 281);
  (void) click_add_element_type("LinkTable", beetlemonkey, 282);
  (void) click_add_element_type("MadwifiRate", beetlemonkey, 283);
  (void) click_add_element_type("PacketStore", beetlemonkey, 284);
  (void) click_add_element_type("PrintTXFeedback", beetlemonkey, 285);
  (void) click_add_element_type("PrintWifi", beetlemonkey, 286);
  (void) click_add_element_type("Prism2Decap", beetlemonkey, 287);
  (void) click_add_element_type("Prism2Encap", beetlemonkey, 288);
  (void) click_add_element_type("ProbeTXRate", beetlemonkey, 289);
  (void) click_add_element_type("PushAnno", beetlemonkey, 290);
  (void) click_add_element_type("RadiotapDecap", beetlemonkey, 291);
  (void) click_add_element_type("RadiotapEncap", beetlemonkey, 292);
  (void) click_add_element_type("ReadAnno", beetlemonkey, 293);
  (void) click_add_element_type("RXStats", beetlemonkey, 294);
  (void) click_add_element_type("SetTXPower", beetlemonkey, 295);
  (void) click_add_element_type("SetTXRate", beetlemonkey, 296);
  (void) click_add_element_type("AssociationRequester", beetlemonkey, 297);
  (void) click_add_element_type("BeaconScanner", beetlemonkey, 298);
  (void) click_add_element_type("BeaconTracker", beetlemonkey, 299);
  (void) click_add_element_type("OpenAuthRequester", beetlemonkey, 300);
  (void) click_add_element_type("ProbeRequester", beetlemonkey, 301);
  (void) click_add_element_type("WepDecap", beetlemonkey, 302);
  (void) click_add_element_type("WepEncap", beetlemonkey, 303);
  (void) click_add_element_type("WifiDecap", beetlemonkey, 304);
  (void) click_add_element_type("WifiDefrag", beetlemonkey, 305);
  (void) click_add_element_type("WifiDupeFilter", beetlemonkey, 306);
  (void) click_add_element_type("WifiEncap", beetlemonkey, 307);
  (void) click_add_element_type("WifiFragment", beetlemonkey, 308);
  (void) click_add_element_type("WifiSeq", beetlemonkey, 309);
  (void) click_add_element_type("WirelessInfo", beetlemonkey, 310);
  CLICK_DMALLOC_REG("nXXX");
}

void
click_unexport_elements()
{
  IPSummaryDump_Anno::static_cleanup();
  IPSummaryDump_ICMP::static_cleanup();
  IPSummaryDumpInfo::static_cleanup();
  IPSummaryDump_IP::static_cleanup();
  IPSummaryDump_Link::static_cleanup();
  IPSummaryDump_Payload::static_cleanup();
  IPSummaryDump_TCP::static_cleanup();
  IPSummaryDump_UDP::static_cleanup();
  CheckIPHeader::static_cleanup();
  IPFieldInfo::static_cleanup();
  IPFilter::static_cleanup();
  IPNameInfo::static_cleanup();
  Script::static_cleanup();
}
