// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olans/test.proto

#ifndef PROTOBUF_olans_2ftest_2eproto__INCLUDED
#define PROTOBUF_olans_2ftest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace ClickTest {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_olans_2ftest_2eproto();
void protobuf_AssignDesc_olans_2ftest_2eproto();
void protobuf_ShutdownFile_olans_2ftest_2eproto();

class Station;

// ===================================================================

class Station : public ::google::protobuf::Message {
 public:
  Station();
  virtual ~Station();
  
  Station(const Station& from);
  
  inline Station& operator=(const Station& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Station& default_instance();
  
  void Swap(Station* other);
  
  // implements Message ----------------------------------------------
  
  Station* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Station& from);
  void MergeFrom(const Station& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string address = 2;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 2;
  inline const ::std::string& address() const;
  inline void set_address(const ::std::string& value);
  inline void set_address(const char* value);
  inline void set_address(const char* value, size_t size);
  inline ::std::string* mutable_address();
  
  // @@protoc_insertion_point(class_scope:ClickTest.Station)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::std::string* address_;
  static const ::std::string _default_address_;
  friend void  protobuf_AddDesc_olans_2ftest_2eproto();
  friend void protobuf_AssignDesc_olans_2ftest_2eproto();
  friend void protobuf_ShutdownFile_olans_2ftest_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Station* default_instance_;
};
// ===================================================================


// ===================================================================

// Station

// required int32 id = 1;
inline bool Station::has_id() const {
  return _has_bit(0);
}
inline void Station::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Station::id() const {
  return id_;
}
inline void Station::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// optional string address = 2;
inline bool Station::has_address() const {
  return _has_bit(1);
}
inline void Station::clear_address() {
  if (address_ != &_default_address_) {
    address_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Station::address() const {
  return *address_;
}
inline void Station::set_address(const ::std::string& value) {
  _set_bit(1);
  if (address_ == &_default_address_) {
    address_ = new ::std::string;
  }
  address_->assign(value);
}
inline void Station::set_address(const char* value) {
  _set_bit(1);
  if (address_ == &_default_address_) {
    address_ = new ::std::string;
  }
  address_->assign(value);
}
inline void Station::set_address(const char* value, size_t size) {
  _set_bit(1);
  if (address_ == &_default_address_) {
    address_ = new ::std::string;
  }
  address_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Station::mutable_address() {
  _set_bit(1);
  if (address_ == &_default_address_) {
    address_ = new ::std::string;
  }
  return address_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ClickTest

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_olans_2ftest_2eproto__INCLUDED
